name: Deploy

on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1 
    - name: Set git tag
      run: |
        git tag `cat version.txt`
        git push --tags
    # - name: Update cocoapods
    #   run: |
    #     export NEW_VERSION=`echo \`agvtool mvers -terse1\``
    #     git clone https://github.com/Appboxo/ios-sdk-binary.git
    #     cp -R AppBoxoSDK.zip ios-sdk-binary/AppBoxoSDK.framework.zip
    #     cd ios-sdk-binary
    #     echo ${NEW_VERSION} > version.txt
    #     git add .
    #     git commit -m "updates AppboxoSDK version to ${NEW_VERSION}"
    #     git push -u origin master
